export const datas = [
    {name: 'plasticbottle',
    category: 'bad',
    imageurl: "./waste-images/plastic-bottle.png",
   },
   {name: 'glassbottle',
   category: 'bad',
   imageurl: "./waste-images/glassbottle.png",
  
   },
   {name: 'metalcan',
   category: 'bad',
   imageurl: "./waste-images/metalcan.png",
   }, 
   {name: 'milkbottle',
   category: 'bad', 
   imageurl: "./waste-images/milk.png",
   },
   {name: 'plasticbag',
   category: 'bad', 
   imageurl: "./waste-images/plasticbag.png",
   },
   //////////
   {name: 'apple-eaten',
   category: 'good', 
   imageurl: "./waste-images/apple-eaten.png",
   },
   {name: 'apple',
   category: 'good', 
   imageurl: "./waste-images/APPLE.png",
   },
   {name: 'banana',
   category: 'good', 
   imageurl: "./waste-images/banana.png",
   },
   {name: 'bread',
   category: 'good', 
   imageurl: "./waste-images/bread.png",
   },
   {name: 'brownpaper',
   category: 'good', 
   imageurl: "./waste-images/brownpaper.png",
   },
   {name: 'carrot',
   category: 'good', 
   imageurl: "./waste-images/carot.png",
   },
   {name: 'crevette',
   category: 'good', 
   imageurl: "./waste-images/crevette.png",
   },
   {name: 'eggshell',
   category: 'good', 
   imageurl: "./waste-images/eggshell2.png",
   },
   {name: 'foodleftovers',
   category: 'bad', 
   imageurl: "./waste-images/foodleftovers.png",
   },
   //////////////////////
   {name: 'garlic',
   category: 'dunno', /////
   imageurl: "./waste-images/garlic.png",
   }, 
   {name: 'lemon',
   category: 'dunno', 
   imageurl: "./waste-images/LEMON.png",
   },
   {name: 'moule',
   category: 'bad', 
   imageurl: "./waste-images/moule.png",
   },
   {name: 'mushroom',
   category: 'good', 
   imageurl: "./waste-images/mushroom.png",
   },
   {name: 'oignons',
   category: 'dunno', 
   imageurl: "./waste-images/oignons.png",
   },
   {name: 'paperbag',
   category: 'good', 
   imageurl: "./waste-images/paper bag.png",
   },
   {name: 'salmon',
   category: 'bad', 
   imageurl: "./waste-images/salmon.png",
   },
  ];